// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class cartinfo {
				/**
				 * 
				 */
				private int cartid;
				/**
				 * 
				 */
				private int productid;
				/**
				 * 
				 */
				private int customerid;
	/**
	 * 
	 * @return 
	 */
	public int getproductid() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getcustomerid() {
	}
	/**
	 * 
	 * @param id 
	 */
	public void setcustomerid(int id) {
	}
	/**
	 * 
	 * @param id 
	 */
	public void setcartid(int id) {
	}
	/**
	 * 
	 * @param cost 
	 */
	public void setproductid(int cost) {
	}
	/**
	 * 
	 * @return 
	 */
	public int getcartid() {
	}
}
