// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class managecartUI {
	/**
	 * 
	 */
	public void proceedtocart() {
	}
	/**
	 * 
	 */
	public void startinterface() {
	}
	/**
	 * 
	 */
	public void removeitem() {
	}
}
