// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class managecart {
	/**
	 * 
	 * @param productid 
	 */
	public void removeout(int productid) {
	}
	/**
	 * 
	 * @param id 
	 */
	public void checkout(int id) {
	}
	/**
	 * 
	 * @return 
	 */
	public int calculateprice() {
	}
}
