// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class orderinfo {
				/**
				 * 
				 */
				private int orderid;
				/**
				 * 
				 */
				private int customerid;
				/**
				 * 
				 */
				private int cost;
				/**
				 * 
				 */
				private EcorePrimitiveTypes.EDate ordertime;
	/**
	 * 
	 * @param id 
	 */
	public void setorderid(int id) {
	}
	/**
	 * 
	 * @return 
	 */
	public int getorderid() {
	}
	/**
	 * 
	 * @param id 
	 */
	public void setcustomerid(int id) {
	}
	/**
	 * 
	 * @return 
	 */
	public int getcustomerid() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getcost() {
	}
	/**
	 * 
	 * @param cost 
	 */
	public void setcost(int cost) {
	}
	/**
	 * 
	 * @return 
	 */
	public EcorePrimitiveTypes.EDate getordertime() {
	}
	/**
	 * 
	 * @param date 
	 */
	public void setordertime(EcorePrimitiveTypes.EDate date) {
	}
}
