// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class productlistUI {
	/**
	 * 
	 */
	public void selectproduct() {
	}
	/**
	 * 
	 */
	public void searchproduct() {
	}
	/**
	 * 
	 */
	public void startinterface() {
	}
}
