// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class registration {
	/**
	 * 
	 * @param password 
	 * @param id 
	 */
	public void checkdatabase(String password, String id) {
	}
	/**
	 * 
	 * @param id 
	 * @param password 
	 */
	public void newaccount(String id, String password) {
	}
	/**
	 * 
	 * @param details 
	 */
	public void getdetails(String details) {
	}
}
