// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class admin {
				/**
				 * 
				 */
				private String username;
				/**
				 * 
				 */
				private String password;
	/**
	 * 
	 * @param name 
	 */
	public void setusername(String name) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getusername() {
	}
	/**
	 * 
	 * @return 
	 */
	public String getpassword() {
	}
	/**
	 * 
	 * @param password 
	 */
	public void setpassword(String password) {
	}
}
