// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class customer {
				/**
				 * 
				 */
				private String password;
				/**
				 * 
				 */
				private String username;
				/**
				 * 
				 */
				private String address;
				/**
				 * 
				 */
				private String phone;
				/**
				 * 
				 */
				private String email;
	/**
	 * 
	 * @param name 
	 */
	public void setusername(String name) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getusername() {
	}
	/**
	 * 
	 * @param password 
	 */
	public void setpassword(String password) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getpassword() {
	}
	/**
	 * 
	 * @param phone 
	 */
	public void setphone(String phone) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getphone() {
	}
	/**
	 * 
	 * @param address 
	 */
	public void setaddress(String address) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getaddress() {
	}
	/**
	 * 
	 * @param email 
	 */
	public void setemail(String email) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getmail() {
	}
}
