// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class placeorder {
	/**
	 * 
	 * @param id 
	 */
	public void addorderentry(int id) {
	}
	/**
	 * 
	 * @param number 
	 */
	public void getphone(String number) {
	}
	/**
	 * 
	 * @return 
	 */
	public int calculateprice() {
	}
}
