// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class productinfo {
				/**
				 * 
				 */
				private String productname;
				/**
				 * 
				 */
				private int productid;
				/**
				 * 
				 */
				private String category;
				/**
				 * 
				 */
				private int price;
				/**
				 * 
				 */
				private int rating;
				/**
				 * 
				 */
				private String brand;
	/**
	 * 
	 * @return 
	 */
	public int getproductid() {
	}
	/**
	 * 
	 * @param id 
	 */
	public void setproductid(int id) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getproductname() {
	}
	/**
	 * 
	 * @param name 
	 */
	public void setproductname(String name) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getcategory() {
	}
	/**
	 * 
	 * @param name 
	 */
	public void setcategory(String name) {
	}
	/**
	 * 
	 * @param rate 
	 */
	public void setrating(int rate) {
	}
	/**
	 * 
	 * @return 
	 */
	public int getrating() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getprice() {
	}
	/**
	 * 
	 * @param price 
	 */
	public void setprice(int price) {
	}
	/**
	 * 
	 * @param name 
	 */
	public void setbrandname(String name) {
	}
	/**
	 * 
	 * @return 
	 */
	public String getbrandname() {
	}
}
