// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class product {
	/**
	 * 
	 * @param productid 
	 */
	public void addtocart(int productid) {
	}
}
