// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class productUI {
	/**
	 * 
	 */
	public void selectproduct () {
	}
	/**
	 * 
	 */
	public void startinterface() {
	}
}
