// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ECB Ecommerce.website;



/************************************************************/
/**
 * 
 */
public class registrationUI {
	/**
	 * 
	 */
	public void newregistration() {
	}
	/**
	 * 
	 */
	public void startinterface() {
	}
}
